### ISSUE TITLE
VIR1 - livrable final

### ISSUE THREAD

**Issue by NicolasGlassey** [CPNV-VIR1/cadavrexski#19]
@menoudyann  @lpodev 

Messieurs,

Je suis un peu emprunté... je n'arrive à mettre la main sur votre livrable pour VIR1. Pourriez-vous le livrer soit ici, soit sur votre dépôt ?

Il est possible que j'ai manqué une notification, je suis engagé dans de nombreux dépôts.

Merci !

**Comment by lpodev** [comment]
@NicolasGlassey,
Oui, vous êtes sur le "mauvais" repos. On a livré sur le repos suivant https://github.com/menoudyann/VIR1-CadavreXski
